# Generated by Django 4.1 on 2023-02-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_dimension',
        ),
    ]
